# Copyright 2026 Digital Envoy, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###############################################################################
# Makefile
#         This is the Makefile to compile the C++ XML API example program
#
# Version:    7.0.0
# Date:       2026
###############################################################################
CC=g++

MY_CFLAGS=-O3 -g -Wall

all: testXMLAPI
clean:
	rm -f ../src/*.o *.o testXMLAPI

.SUFFIXES: .cpp .o .h

MY_OBJS=../src/XMLResponse.o testXMLAPI.o

CFLAGS=-I../include `xml2-config --cflags`

LIBS=`xml2-config --libs`

testXMLAPI: $(MY_OBJS)
	@echo "============="
	@echo "Linking $@"
	@$(CC) -o testXMLAPI $(MY_OBJS) $(LIBS)

## Generic compilation rule
%.o : %.cpp
	@echo "============="
	@echo "Compiling $<"
	@$(CC) $(CFLAGS) -c $< -o $@ $(LIBS)

../src/%.o : ../src/%.cpp
	@echo "============="
	@echo "Compiling $<"
	@$(CC) $(CFLAGS) -c $< -o $@ $(LIBS)
